//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string Passport { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Card { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
    
        public virtual Occupations Occupations { get; set; }
    }
}
